
### Buscar todos os agendamentos (GET ALL)
GET http://localhost:8080/api/agendamentos
Accept: application/json


### Criar novo agendamento (POST)
POST http://localhost:8080/api/agendamentos
Content-Type: application/json

{
    "titulo": "Reunião Maluca",
    "descricao": "teste",
    "dataInicio": "2025-10-26T16:02:00",
    "dataFim": "2026-10-10T20:00:00",
    "usuario": "ricardo"
}

