spring.application.name=miniagendamento
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_agendamento
spring.datasource.username=postgres
# Usa as configurações de 'dev' se o perfil estiver ativo
spring.profiles.active=dev
spring.datasource.password=${DB_PASSWORD:manager}

# Configurações de JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
# Talvez tenha que muda de update para None, depende da config.
spring.jpa.show-sql=true